import importlib.util
import inspect
import sys
from argparse import ArgumentParser
from dataclasses import dataclass
from pathlib import Path
from time import sleep
from typing import Any

from plcm import Lcm


@dataclass
class NestedAttributes:
    attributes: list[tuple[str, Any]]


_stored_fingerprints = {}


def create_argparser() -> ArgumentParser:
    argparser = ArgumentParser(
        prog="spy",
        description="Replacement for Java-based lcm-spy that ships with lcm.",
    )

    argparser.add_argument(
        "-l",
        "--lcm-url",
        default="tcpq://",
        help="A url containing the provider, address, port number, and various"
        " other options (where relevant). E.g. tcpq:// or udpm://239.255.76.67:7667?ttl=1"
        " or providername://127.0.0.1. How those values and options are handled"
        " and processed is up to the underyling provider implementation.",
    )

    argparser.add_argument(
        "-g",
        "--generated-messages",
        type=Path,
        default=None,
        help="Path to directory containing files generated by lcmgen."
        " Must be Python files.",
    )

    return argparser


def expand_message(message: Any) -> list[tuple[str, Any]]:
    attributes = inspect.getmembers(message, lambda a: not inspect.isroutine(a))
    attributes = [
        attribute for attribute in attributes if not attribute[0].startswith("_")
    ]

    for idx, attribute in enumerate(attributes):
        if hasattr(attribute[1], "_get_packed_fingerprint"):
            attributes[idx] = (
                attribute[0],
                (
                    attribute[1].__class__.__name__,
                    NestedAttributes(expand_message(attribute[1])),
                ),
            )

    return attributes


def receive_message(channel: str, data: bytes) -> None:
    decode = _stored_fingerprints.get(data[:8])

    if decode is None:
        return

    message = decode(data)
    attributes = expand_message(message)

    print(channel, attributes)


def store_fingerprint_mappings(path: Path | None = None) -> None:
    if path is None:
        return

    spec = importlib.util.spec_from_file_location(
        path.stem, (path / "__init__.py").as_posix()
    )

    if spec is None or spec.loader is None:
        return

    module = importlib.util.module_from_spec(spec)
    sys.modules[path.stem] = module
    spec.loader.exec_module(module)

    for cls_member in inspect.getmembers(module, inspect.isclass):
        get_packed_fingerprint = getattr(cls_member[1], "_get_packed_fingerprint", None)

        if get_packed_fingerprint is None:
            continue

        _stored_fingerprints[get_packed_fingerprint()] = cls_member[1].decode


def main() -> None:
    arguments = create_argparser().parse_args()

    store_fingerprint_mappings(arguments.generated_messages)

    plc = Lcm().connect(arguments.lcm_url)
    plc.subscribe(r".+", receive_message)

    sleep(30)


if __name__ in {"__main__", "__mp_main__"}:
    main()
