import importlib.util
import inspect
import sys
from argparse import ArgumentParser
from dataclasses import dataclass
from pathlib import Path
from threading import Lock
from time import time_ns
from typing import Any

from textual.app import App, ComposeResult
from textual.containers import Center
from textual.widgets import Button, DataTable

from plcm import Lcm

COLUMNS = (
    "Channel",
    "Type",
    "Num Msgs",
    "Hz",
    "1/Hz",
    "Jitter",
    "Bandwidth",
    "Undecodable",
)


@dataclass
class NestedAttributes:
    attributes: list[tuple[str, Any]]


@dataclass
class TemporaryChannelData:
    data_size: int = 0
    last_update_time: int = 0
    last_message_time: int = 0
    min_interval: int = 9999
    max_interval: int = 0
    last_received_count: int = 0


@dataclass
class ChannelData:
    channel: str
    cls: Any

    temporary_data: TemporaryChannelData

    received_count: int = 0


def create_argparser() -> ArgumentParser:
    argparser = ArgumentParser(
        prog="spy",
        description="Replacement for Java-based lcm-spy that ships with lcm.",
    )

    argparser.add_argument(
        "-l",
        "--lcm-url",
        default="tcpq://",
        help="A url containing the provider, address, port number, and various"
        " other options (where relevant). E.g. tcpq:// or udpm://239.255.76.67:7667?ttl=1"
        " or providername://127.0.0.1. How those values and options are handled"
        " and processed is up to the underyling provider implementation.",
    )

    argparser.add_argument(
        "-g",
        "--generated-messages",
        type=Path,
        default=None,
        help="Path to directory containing files generated by lcmgen."
        " Must be Python files.",
    )

    return argparser


class UI(App):
    def __init__(self) -> None:
        super().__init__()

        self._table = None
        self._channel_data_lock = Lock()
        self._last_messages: dict[str, list[tuple[str, Any]]] = {}
        self._channel_data: dict[str, ChannelData] = {}
        self._stored_fingerprints = {}

        arguments = create_argparser().parse_args()
        self.store_fingerprint_mappings(arguments.generated_messages)

        plc = Lcm().connect(arguments.lcm_url)
        plc.subscribe(r".+", self.receive_message)

    def compose(self) -> ComposeResult:
        yield DataTable()
        with Center():
            yield Button("Clear", id="clear", flat=True, compact=True)

    def on_mount(self) -> None:
        table = self.query_one(DataTable)
        table.add_columns(*[(column, column) for column in COLUMNS])
        self.set_interval(1, self._update_table)

    def on_button_pressed(self, event: Button.Pressed) -> None:
        if event.button.id == "clear":
            table = self.query_one(DataTable)
            with self._channel_data_lock:
                for channel in self._channel_data:
                    if channel in table.rows:
                        table.remove_row(channel)

                self._channel_data = {}

    def _update_table(self) -> None:
        table = self.query_one(DataTable)

        with self._channel_data_lock:
            for channel_data in self._channel_data.values():
                current_time = time_ns()
                received_since_last = (
                    channel_data.received_count
                    - channel_data.temporary_data.last_received_count
                )
                time_since_last = (
                    current_time - channel_data.temporary_data.last_update_time
                ) / 1e9
                frequency = received_since_last / time_since_last
                jitter = (
                    channel_data.temporary_data.max_interval
                    - channel_data.temporary_data.min_interval
                ) / 1e6
                bandwidth = (
                    channel_data.temporary_data.data_size / time_since_last
                ) / 1024

                row = (
                    channel_data.channel,
                    channel_data.cls.__name__,
                    channel_data.received_count,
                    frequency,
                    f"{(1_000 / frequency if frequency > 0 else float('inf')):6.2f} ms",
                    f"{jitter:6.2f} ms",
                    f"{bandwidth:6.2f} KB/s",
                    0,
                )

                channel_data.temporary_data.min_interval = 1_000_000_000
                channel_data.temporary_data.max_interval = 0
                channel_data.temporary_data.last_received_count = (
                    channel_data.received_count
                )
                channel_data.temporary_data.data_size = 0
                channel_data.temporary_data.last_update_time = current_time

                if channel_data.channel in table.rows:
                    for idx in range(len(COLUMNS)):
                        table.update_cell(channel_data.channel, COLUMNS[idx], row[idx])
                else:
                    table.add_row(*row, key=channel_data.channel)

    def expand_message(self, message: Any) -> list[tuple[str, Any]]:
        attributes = inspect.getmembers(message, lambda a: not inspect.isroutine(a))
        attributes = [
            attribute for attribute in attributes if not attribute[0].startswith("_")
        ]

        for idx, attribute in enumerate(attributes):
            if hasattr(attribute[1], "_get_packed_fingerprint"):
                attributes[idx] = (
                    attribute[0],
                    (
                        attribute[1].__class__.__name__,
                        NestedAttributes(self.expand_message(attribute[1])),
                    ),
                )

        return attributes

    def receive_message(self, channel: str, data: bytes) -> None:
        decode = self._stored_fingerprints.get(data[:8])

        if decode is None:
            # TODO: Add display capability for undecodable messages.
            return

        data_size = len(channel) + len(data)
        message = decode(data)

        self._last_messages[channel] = self.expand_message(message)

        with self._channel_data_lock:
            if channel not in self._channel_data:
                self._channel_data[channel] = ChannelData(
                    channel=channel,
                    cls=message.__class__,  # TODO: Not yet utilized for anything.
                    temporary_data=TemporaryChannelData(),
                )

            channel_data = self._channel_data[channel]

            current_time = time_ns()
            interval = current_time - channel_data.temporary_data.last_message_time
            channel_data.temporary_data.min_interval = min(
                channel_data.temporary_data.min_interval, interval
            )
            channel_data.temporary_data.max_interval = max(
                channel_data.temporary_data.max_interval, interval
            )
            channel_data.temporary_data.last_message_time = current_time

            channel_data.received_count += 1
            channel_data.temporary_data.data_size += data_size

    def store_fingerprint_mappings(self, path: Path | None = None) -> None:
        if path is None:
            return

        spec = importlib.util.spec_from_file_location(
            path.stem, (path / "__init__.py").as_posix()
        )

        if spec is None or spec.loader is None:
            return

        module = importlib.util.module_from_spec(spec)
        sys.modules[path.stem] = module
        spec.loader.exec_module(module)

        for cls_member in inspect.getmembers(module, inspect.isclass):
            get_packed_fingerprint = getattr(
                cls_member[1], "_get_packed_fingerprint", None
            )

            if get_packed_fingerprint is None:
                continue

            self._stored_fingerprints[get_packed_fingerprint()] = cls_member[1].decode


def main() -> None:
    app = UI()
    app.run()


if __name__ == "__main__":
    main()
